---
- name: Gotify Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gotify_data_directory }}/app/data"

- name: Gotify Docker Container
  docker_container:
    name: gotify
    image: gotify/server:latest
    pull: true
    volumes:
      - "{{ gotify_data_directory }}/data:/app/data:rw"
    ports:
      - "{{ gotify_port_http }}:80"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ gotify_user_id }}"
      PGID: "{{ gotify_group_id }}"
    restart_policy: unless-stopped
    labels:
      traefik.backend: "gotify"
      traefik.frontend.rule: "Host:gotify.{{ ansible_nas_domain }}"
      traefik.enable: "{{ gotify_available_externally }}"
      traefik.port: "80"
    memory: 1g
